### ISSUE TITLE
docs: update dependabot workflow to add commit message and label

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1812]
### what's wrong with the documentation?

> Current One:

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

Firstly, it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

### Add screenshots

> looks clean and according to conventions
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5f7ae417-b0d8-44bc-89e0-0ba02621979e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
